### PR TITLE
Music commands

### PR DESCRIPTION
**Pull request by MutlaqAldhbuiub**
### UPDATED ###

* server must have ``` sudo apt install ffmpeg ```
* make sure about **all** npm packages are installed **successfully**
* currently only works with youtube because ``` ytdl-core ```

* I think also you need ``` npm i opusscript ``` but I'm not that sure becuase I replace it with ``` npm i @discordjs/opus ```

### CODE REVIEW

**Comment by sudomaze** [comment]
For the `node_modules`, I was actually planning to remove it. I just added it inside `.gitignore` to be ignored when pushing. Some packages can't be run on all of operating systems, so you would need to rerun `npm install` to get the right package version for your OS.

**Comment by sudomaze** [comment]
I got these errors when trying to play a song: 

`Error: input stream: Could not find player config`

and

`Error: input stream: Video unavailable`

**Comment by MutlaqAldhbuiub** [comment]
> I got these errors when trying to play a song:
> 
> `Error: input stream: Could not find player config`
> 
> and
> 
> `Error: input stream: Video unavailable`

make sure that you have FFempg installed on your system
```bash
sudo apt install ffmpeg
```
then make sure about ``` npm install  @discordjs/opus ```
and also make sure about ``` npm install ytdl-core```

**Review by Mo9a7i — APPROVED** [review]
Thank you Shnboo

**Comment by sudomaze** [comment]
I have `FFmpeg` on my machine. I will test it again tomorrow and let you know.

**Comment by Mo9a7i** [comment]
will test it on a fresh ubuntu installation and see

**Comment by sudomaze** [comment]
I have tried to reset the environment using the following commands:
```
sudo apt install ffmpeg
npm install @discordjs/opus
npm install ytdl-core
```
 worked! Until it broke.

I think the pause and resume functionality has some issues either because I have passed a playlist or it is something else.

Here is a sample of the error:

```Error [ERR_STREAM_WRITE_AFTER_END]:```

**Comment by sudomaze** [comment]
Also, when the bot gets disconnected and asks to play a song, it adds it to the queue but it doesn't actually join the voice channel and play the song.

**Comment by MutlaqAldhbuiub** [comment]
@sudogroup/devs 
Hola,
First of all, 
I am so sorry for being late to update and solve the problem.
second 
I've tried the bot in my home server "Ubuntu 16.04.7 LTS", and also my home machine "Ubuntu 20.04.1 LTS"
both of them are brand new operating system.
I haven't found/seen any issue with the code itself.
The problem I've faced is :
```
Error: input stream: Could not find player config
```
to solve this problem you need to make sure that ``` m3u8stream ``` installed by type the following command.
```
npm install m3u8stream
```

So, 
If you have any problem you should type those command
```
npm install
sudo apt-get install g++
npm install m3u8stream
npm install ytdl-core@latest
npm i @discordjs/opus
```
__You could skip g++ if you're using a Windows machine.__

**Comment by Mo9a7i** [comment]
how about you add the m3u8stream to the packages.json by using `npm install m3u8stream --save` if it is a necessary dependancy
also, how do we do g++ in windows, do we need it ?

**Comment by sudomaze** [comment]
Updated PR: #38

**Pull request closed without merging**
